#!/bin/bash
################################################################################
# Export Pipeline Outputs to Thesis Production Folder
# ====================================================
# Runs the full empirics pipeline and exports outputs to thesis structure
#
# Paths (Mac):
#   Code:   /Users/hyunjimoon/tolzul/Front/On/love(cs)/strategic_ambiguity/empirics
#   Output: /Users/hyunjimoon/tolzul/Front/On/love(cs)/thesis/⚙️process/3️⃣_OUTPUT
#
# Thesis Output Structure:
#   3️⃣_OUTPUT/
#   ├── Theory/
#   │   ├── fig1_tradeoff.pdf
#   │   └── fig2_architecture.pdf
#   ├── Empirics_Early/
#   │   ├── fig3_H1_scatter.pdf
#   │   └── table1_H1_regression.txt
#   └── Empirics_Later/
#       ├── fig4_vxh_interaction.pdf
#       └── table2_H2_logit.txt
#
# Usage:
#   ./export_to_thesis.sh              # Run full pipeline + export
#   ./export_to_thesis.sh --quick      # Skip data loading
#   ./export_to_thesis.sh --dataset all  # Specify dataset
################################################################################

set -e  # Exit on error
set -u  # Exit on undefined variable

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ============================================================================
# PATH CONFIGURATION
# ============================================================================
# Note: These paths are for Mac. Adjust if running elsewhere.
EMPIRICS_DIR="/Users/hyunjimoon/tolzul/Front/On/love(cs)/strategic_ambiguity/empirics"
THESIS_OUTPUT_DIR="/Users/hyunjimoon/tolzul/Front/On/love(cs)/thesis/⚙️process/3️⃣_OUTPUT"

# Check if we're in the right directory
if [ ! -d "pipeline" ]; then
    echo -e "${RED}Error: Must run from empirics directory${NC}"
    echo "Expected directory: $EMPIRICS_DIR"
    exit 1
fi

# Create thesis output directories
mkdir -p "$THESIS_OUTPUT_DIR/Theory"
mkdir -p "$THESIS_OUTPUT_DIR/Empirics_Early"
mkdir -p "$THESIS_OUTPUT_DIR/Empirics_Later"

# ============================================================================
# HEADER
# ============================================================================
echo -e "${CYAN}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${CYAN}     Thesis Export: Pipeline → Production Folder${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${BLUE}Source:${NC}  $EMPIRICS_DIR"
echo -e "${BLUE}Output:${NC}  $THESIS_OUTPUT_DIR"
echo ""

START_TIME=$(date +%s)

# ============================================================================
# STEP 1-5: Run Full Pipeline
# ============================================================================
echo -e "${YELLOW}▶ Running Full Analysis Pipeline${NC}"
echo "────────────────────────────────────────────────────────────────────"
./run_all.sh "$@"
echo ""

# ============================================================================
# STEP 6: Generate Additional Figures
# ============================================================================
echo -e "${YELLOW}▶ STEP 6: Generate Thesis-Specific Figures${NC}"
echo "────────────────────────────────────────────────────────────────────"
python3 thesis_figures.py
echo ""

# ============================================================================
# STEP 7: Export to Thesis Structure
# ============================================================================
echo -e "${YELLOW}▶ STEP 7: Export to Thesis Production Folder${NC}"
echo "────────────────────────────────────────────────────────────────────"

# Determine which dataset to export (default: all)
DATASET="${1:-all}"
if [[ "$DATASET" == "--quick" ]] || [[ "$DATASET" == "--dataset" ]]; then
    DATASET="all"
fi

echo -e "${BLUE}Exporting dataset: $DATASET${NC}"
echo ""

# Theory - Conceptual figures (generated by thesis_figures.py)
echo "📊 Theory..."
if [ -f "outputs/$DATASET/figures/fig1_tradeoff.pdf" ]; then
    cp outputs/$DATASET/figures/fig1_tradeoff.pdf "$THESIS_OUTPUT_DIR/Theory/"
    echo "  ✓ fig1_tradeoff.pdf"
fi
if [ -f "outputs/$DATASET/figures/fig2_architecture.pdf" ]; then
    cp outputs/$DATASET/figures/fig2_architecture.pdf "$THESIS_OUTPUT_DIR/Theory/"
    echo "  ✓ fig2_architecture.pdf"
fi

# Empirics_Early - H1 test (E ~ V)
echo "📊 Empirics_Early (H1)..."
if [ -f "outputs/$DATASET/figures/fig3_H1_scatter.pdf" ]; then
    cp outputs/$DATASET/figures/fig3_H1_scatter.pdf "$THESIS_OUTPUT_DIR/Empirics_Early/"
    echo "  ✓ fig3_H1_scatter.pdf"
fi
if [ -f "outputs/$DATASET/models/h1_coefficients.csv" ]; then
    # Convert CSV to formatted TXT
    python3 -c "
import pandas as pd
df = pd.read_csv('outputs/$DATASET/models/h1_coefficients.csv')
with open('$THESIS_OUTPUT_DIR/Empirics_Early/table1_H1_regression.txt', 'w') as f:
    f.write('═══════════════════════════════════════════════════════════════════\n')
    f.write('H1 REGRESSION: Early Funding ~ Vagueness\n')
    f.write('═══════════════════════════════════════════════════════════════════\n\n')
    f.write('DV: series_a_amount (log-transformed)\n')
    f.write('Key hypothesis: β(vagueness) < 0 (more vague → less funding)\n\n')
    f.write(df.to_string(index=False))
    f.write('\n\nDataset: $DATASET\n')
    f.write('N = ' + str(len(pd.read_csv('outputs/$DATASET/models/h2_analysis_dataset.csv'))) + '\n')
"
    echo "  ✓ table1_H1_regression.txt"
fi

# Empirics_Later - H2 test (L ~ V×H)
echo "📊 Empirics_Later (H2)..."
if [ -f "outputs/$DATASET/figures/F3a_interaction.pdf" ]; then
    cp outputs/$DATASET/figures/F3a_interaction.pdf "$THESIS_OUTPUT_DIR/Empirics_Later/fig4_vxh_interaction.pdf"
    echo "  ✓ fig4_vxh_interaction.pdf (V×H interaction - THE MONEY PLOT)"
fi
if [ -f "outputs/$DATASET/models/h2_main_coefficients.csv" ]; then
    # Convert CSV to formatted TXT
    python3 -c "
import pandas as pd
df = pd.read_csv('outputs/$DATASET/models/h2_main_coefficients.csv')
with open('$THESIS_OUTPUT_DIR/Empirics_Later/table2_H2_logit.txt', 'w') as f:
    f.write('═══════════════════════════════════════════════════════════════════\n')
    f.write('H2 LOGISTIC REGRESSION: Later Success ~ Vagueness × Hardware\n')
    f.write('═══════════════════════════════════════════════════════════════════\n\n')
    f.write('DV: series_b_plus (binary: 0=No Series B+, 1=Yes Series B+)\n')
    f.write('Key hypotheses:\n')
    f.write('  H2a: β(vagueness) < 0 for software (main effect)\n')
    f.write('  H2b: β(vagueness × hardware) < 0 (interaction - scissors pattern)\n\n')
    f.write(df.to_string(index=False))
    f.write('\n\nDataset: $DATASET\n')
    f.write('N = ' + str(len(pd.read_csv('outputs/$DATASET/models/h2_analysis_dataset.csv'))) + '\n')
"
    echo "  ✓ table2_H2_logit.txt"
fi

echo ""

# ============================================================================
# SUMMARY
# ============================================================================
END_TIME=$(date +%s)
ELAPSED=$((END_TIME - START_TIME))
MINUTES=$((ELAPSED / 60))
SECONDS=$((ELAPSED % 60))

echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✓ EXPORT COMPLETE${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "Total time: ${GREEN}${MINUTES}m ${SECONDS}s${NC}"
echo ""
echo -e "${CYAN}📂 Thesis Output Directory:${NC}"
echo "  $THESIS_OUTPUT_DIR"
echo ""
echo -e "${CYAN}📊 Generated Files:${NC}"

# Count files in each section
THEORY_COUNT=$(find "$THESIS_OUTPUT_DIR/Theory" -type f 2>/dev/null | wc -l | tr -d ' ')
EARLY_COUNT=$(find "$THESIS_OUTPUT_DIR/Empirics_Early" -type f 2>/dev/null | wc -l | tr -d ' ')
LATER_COUNT=$(find "$THESIS_OUTPUT_DIR/Empirics_Later" -type f 2>/dev/null | wc -l | tr -d ' ')

echo "  Theory/           ($THEORY_COUNT files)"
echo "    - fig1_tradeoff.pdf"
echo "    - fig2_architecture.pdf"
echo ""
echo "  Empirics_Early/   ($EARLY_COUNT files)"
echo "    - fig3_H1_scatter.pdf"
echo "    - table1_H1_regression.txt"
echo ""
echo "  Empirics_Later/   ($LATER_COUNT files)"
echo "    - fig4_vxh_interaction.pdf (THE MONEY PLOT)"
echo "    - table2_H2_logit.txt"
echo ""

# Check if all expected files exist
EXPECTED_FILES=(
    "$THESIS_OUTPUT_DIR/Theory/fig1_tradeoff.pdf"
    "$THESIS_OUTPUT_DIR/Theory/fig2_architecture.pdf"
    "$THESIS_OUTPUT_DIR/Empirics_Early/fig3_H1_scatter.pdf"
    "$THESIS_OUTPUT_DIR/Empirics_Early/table1_H1_regression.txt"
    "$THESIS_OUTPUT_DIR/Empirics_Later/fig4_vxh_interaction.pdf"
    "$THESIS_OUTPUT_DIR/Empirics_Later/table2_H2_logit.txt"
)

MISSING=0
for file in "${EXPECTED_FILES[@]}"; do
    if [ ! -f "$file" ]; then
        echo -e "${YELLOW}⚠ Missing: $(basename $file)${NC}"
        MISSING=$((MISSING + 1))
    fi
done

if [ $MISSING -eq 0 ]; then
    echo -e "${GREEN}✓ All expected files generated successfully!${NC}"
else
    echo -e "${YELLOW}⚠ $MISSING file(s) missing. Check thesis_figures.py or pipeline outputs.${NC}"
fi

echo ""
echo -e "${CYAN}Next steps:${NC}"
echo "  1. Review figures in $THESIS_OUTPUT_DIR"
echo "  2. Copy production draft.md files to each section"
echo "  3. Run bash run_all.sh from thesis/2️⃣_PRODUCTION/"
echo ""
echo -e "${GREEN}Ready for thesis defense! 🎓${NC}"
echo ""
