# Michel Bierlaire
# Thu Nov  1 16:15:41 2018

import pandas as pd
import biogeme.database as db
import biogeme.biogeme as bio
import biogeme.models as models
from biogeme.models import logit
from biogeme.expressions import Beta, DefineVariable, log
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("optimaDataset.dat",'\t')
database = db.Database("optimaDataset",df)
pd.options.display.float_format = '{:.3g}'.format
globals().update(database.variables)


### The condition CostCarCHF was not originally there.
exclude =  ((Choice == -1) + (  CostCarCHF   <  0  )) >0
database.remove(exclude)


### Normalize the weights
# The weights are normalized to guarantee that their sum is the sample size
sumWeight = database.data['Weight'].sum()
S = database.getSampleSize()
sampleNormalizedWeight = Weight * S / sumWeight
# Assume that the total population contains 1 million individuals.
N = 1000000


#Parameters to be estimated
# Arguments:
#   1  Name for report. Typically, the same as the variable
#   2  Starting value
#   3  Lower bound
#   4  Upper bound
#   5  0: estimate the parameter, 1: keep it fixed
ASC_CAR	 = Beta('ASC_CAR',0,None,None,0)
ASC_SM	 = Beta('ASC_SM',0,None,None,0)
ASC_PT	 = Beta('ASC_PT',0,None,None,1)
BETA_COST	 = Beta('BETA_COST',0,None,None,0)
BETA_DIST	 = Beta('BETA_DIST',0,None,None,0)
BETA_TIME	 = Beta('BETA_TIME',0,None,None,0)

# Define here arithmetic expressions for name that are not directly
# available from the data
#Utilities
CAR = ASC_CAR + BETA_TIME * TimeCar + BETA_COST * CostCarCHF
SM = ASC_SM + BETA_DIST * distance_km
PT = ASC_PT + BETA_TIME * TimePT + BETA_COST * MarginalCostPT
V = {1: CAR,2: SM,0: PT}
av = {1: 1,2: 1,0: 1}


# Logit model, with availability conditions
logprob = models.loglogit(V,av,Choice)
biogeme  = bio.BIOGEME(database,logprob)
biogeme.modelName = "logit_generic_optima"
results = biogeme.estimate()

def scenario(costScale):
    theCost = MarginalCostPT * costScale
    PT = ASC_PT + BETA_TIME * TimePT + BETA_COST * theCost
    V = {1: CAR,2: SM,0: PT}
    prob_pt = logit(V,av,0)
    simulate = {'Weighted prob. PT': sampleNormalizedWeight * prob_pt,
                'Weighted rev. PT': sampleNormalizedWeight * prob_pt * theCost}
    biosim  = bio.BIOGEME(database,simulate)
    biosim.modelName = f"revenues_pt_{costScale}"
    simresults = biosim.simulate(dict(zip(results.data.betaNames, results.data.betaValues)))
    return 100*simresults['Weighted prob. PT'].mean(),simresults['Weighted rev. PT'].sum() * N / S


scales = np.arange(0.8,1.7,0.1)
shares,revs = zip(*[scenario(s) for s in scales])


plt.xlabel("Modification of PT cost (%)")
plt.ylabel("Revenues generated by PT (CHF)")
plt.plot(100*scales,revs)

plt.show()

plt.xlabel("Modification of PT cost (%)")
plt.ylabel("Market shares for PT (%)")
plt.plot(100*scales,shares)

plt.show()
